### ISSUE TITLE
Question about evaluation metric.

### ISSUE THREAD

**Issue by lotusroot-kim** [kmaninis/OSVOS-PyTorch#15]
Hi, thanks for nice code about OSVOS.
Is there any evaluation Pytorch-code? (about Region Similarity, Contour Accuracy, Temporal stability).
I hope the reply.
Thank.

**Comment by kmaninis** [comment]
Hi, thanks for the nice words. For DAVIS there is [this](https://github.com/fperazzi/davis) repo that evaluates results in Python. Hope this helps.
