### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by ybrunken** [kmaninis/OSVOS-PyTorch#19]
I'm experiencing a very high CPU usage running the train_online.py file with the default settings. Is this normal? It increases from 30% to around 95% on all 36 available cores.

OS: Ubuntu 16.04
PyTorch: 0.4.1.post2
CUDA: 9.0
Python: 3.7.0

Thanks,
Yannick

**Comment by kmaninis** [comment]
Hello, even though I have never tried your configuration, executing the following before running the script should fix the issue:
`export OMP_NUM_THREADS=4`
You can change 4 for the desired number of threads.
Let me know in case the issue is not fixed.

**Comment by ybrunken** [comment]
Thanks a lot, that does the job! :)
