### ISSUE TITLE
Confused by " inputs.requires_grad_()"

### ISSUE THREAD

**Issue by InstantWindy** [kmaninis/OSVOS-PyTorch#22]
Hello! I don't understand the meaning of this code，Why should input be derivable?if inputs.requires_grad_()，the attribute of inputs requires_grad is true,that means input is derivable.I don't why .Thank you !

**Comment by kmaninis** [comment]
You are right, it doesn't need to be. I think I accidentally did that while upgrading PyTorch from 0.3 (where Variable() was necessary) to 0.4. Will update ASAP, but this line doesn't change the network's behavior.

**Comment by InstantWindy** [comment]
Thank you ! But I think it will affect the weight update!

**Comment by kmaninis** [comment]
How?
