### ISSUE TITLE
can you help me, how to use this code on Davis 2017

### ISSUE THREAD

**Issue by zouying-sjtu** [kmaninis/OSVOS-PyTorch#31]
how to use osvos-pytorch on Davis2017, there are several objects in one sequence.

**Comment by kmaninis** [comment]
Hi, we use exactly the same approach for DAVIS 2017. We fine-tune on each instance separately, and merge the results of multiple objects by assigning the argmax of the probabilities as the object id.

**Comment by zouying-sjtu** [comment]
thanks for your help
