### ISSUE TITLE
Optimizer learning rates

### ISSUE THREAD

**Issue by Adeel-Abdullah** [kmaninis/OSVOS-PyTorch#35]
What’s the basis of setting different learning rates in optimizer for each parameter of the network? Are these learning rates based on an existing research, or are they randomly set at first and then finetuned by you?

**Comment by scaelles** [comment]
Hello,
A similar network structure architecture than the one used in OSVOS was used in [COB](https://github.com/kmaninis/COB). Therefore, we use the same training strategy than that work.
