### ISSUE TITLE
Question about evaluation result

### ISSUE THREAD

**Issue by weirme** [kmaninis/OSVOS-PyTorch#36]
Hello, I have run the code and got the segmentation of each video after 10000 epoch online training, but the evaluation result is lower than that in the paper. I wonder if there are some tricks to improve the result or just that I made some mistakes in this process? Thanks!

**Comment by scaelles** [comment]
Hello,

In order to reproduce the exacts numbers from the paper you should use the [caffe](https://github.com/kmaninis/OSVOS-caffe) repository. This repository does not contain the boundary snapping part (and we are not planning to port it due to its integration with Matlab).
