### ISSUE TITLE
an error occurred when running train_parent.py

### ISSUE THREAD

**Issue by ghost** [kmaninis/OSVOS-PyTorch#37]
python train_parent.py
Using GPU: 0
Constructing OSVOS architecture..
Initializing weights..
Loading weights from Caffe VGG
Traceback (most recent call last):
  File "train_parent.py", line 112, in <module>
    db_train = db.DAVIS2016(train=True, inputRes=None, db_root_dir=db_root_dir, transform=composed_transforms)
  File "/home/fcy/OSVOS_PyTorch/dataloaders/davis_2016.py", line 46, in __init__
    with open(os.path.join(db_root_dir, fname + '.txt')) as f:
FileNotFoundError: [Errno 2] No such file or directory: './DAVIS/train_seqs.txt'
there is no 'train_seqs.txt', where is the file?could u plz tell me how to get the file?thx,

**Comment by kmaninis** [comment]
Please take a look at step 3 of training the parent network, and let me know if it works.

**Comment by ghost** [comment]
thx. I don't know if you mean that I should put the train.txt and val.txt in /ImageSets/480p into the DAVIS root folder and I need rename them as train_seqs.txt and val_seqs.txt?

**Comment by kmaninis** [comment]
The files are already renamed. Did it work?

**Comment by ghost** [comment]
there is no the file ./DAVIS/train_seqs.txt and you don't provide that file. I don't know how to get it.  Idon't what the step 3 means and it's wrong that I **put the train.txt and val.txt in /ImageSets/480p into the DAVIS root folder and I need rename them as train_seqs.txt and val_seqs.txt**. After that, when runing train_parent.py. Idon't know why.
python train_parent.py 
Using GPU: 7 
Constructing OSVOS architecture..
Initializing weights..
Loading weights from Caffe VGG
Traceback (most recent call last):
  File "train_parent.py", line 112, in <module>
    db_train = db.DAVIS2016(train=True, inputRes=None, db_root_dir=db_root_dir, transform=composed_transforms)
  File "/home/fcy/OSVOS_PyTorch/dataloaders/davis_2016.py", line 46, in __init__
    images = np.sort(os.listdir(os.path.join(db_root_dir, 'JPEGImages/480p/', seq.strip())))
FileNotFoundError: [Errno 2] No such file or directory: '/JPEGImages/480p/bear/00000.jpg /Annotations/480p/bear/00000.png'

**Comment by scaelles** [comment]
The path of the errors looks suspicious to me, did you set up the correct `db_root_dir` in [mypath.py](https://github.com/kmaninis/OSVOS-PyTorch/blob/master/mypath.py#L7)?

**Comment by kmaninis** [comment]
Also, the files can be downloaded from here: [[train](https://github.com/kmaninis/OSVOS-PyTorch/files/1938742/train_seqs.txt), [val](https://github.com/kmaninis/OSVOS-PyTorch/files/1938743/val_seqs.txt)]
