### ISSUE TITLE
OSVOS Contour Branch code in PyTorch

### ISSUE THREAD

**Issue by omkar13** [kmaninis/OSVOS-PyTorch#4]
Hey, It would be great if we could have the entire OSVOS code (including Contour Branch) ported to PyTorch so that we can reproduce the results in the paper and implement our own ideas on top of it. Thanking you in anticipation.

**Comment by kmaninis** [comment]
Hi,

The contour branch is available in the Caffe repo of OSVOS. It is implemented in Matlab and C++, and implementing it in python would require quite a lot of time so we are not planning to do it.
