### ISSUE TITLE
Check on a video

### ISSUE THREAD

**Issue by dharma-kc** [kmaninis/OSVOS-PyTorch#6]
Can you guys explain how do I check the generated models on a video. Thank you.

**Comment by scaelles** [comment]
This method works in a per frame basis, so if you have a video you have to decode it in frames (using for example ffmpeg), apply our method and then create again the video with the result. I hope this answers your question.

**Comment by Minotaur-CN** [comment]
If using video sample. How to add first frame segmentation result to the tesing phase. Or using train_online.py at first, and then apply the test code

**Comment by scaelles** [comment]
The train_online.py scripts first trains for the specific object instance in the first frame that you would like to segment and then it generates the result for all the frames in the video sequence.

**Comment by Minotaur-CN** [comment]
That means only the first frame need train_online.py, after that , the following steps only input rgb frame, no more mask frame needed. 
2 . mask frame only needed on train_parent and train_online.

Am I understood right?

**Comment by scaelles** [comment]
> That means only the first frame need train_online.py, after that , the following steps only input rgb frame, no more mask frame needed.

That's right!

> 2 . mask frame only needed on train_parent and train_online.

I am not sure what you exactly mean. In order to train the parent model you need the mask for all the frames in the video so the network can learn saliency.
