### ISSUE TITLE
Unable to run train_online.py

### ISSUE THREAD

**Issue by mrteera** [kmaninis/OSVOS-PyTorch#7]
```
# python train_online.py
Constructing OSVOS architecture..
Initializing weights..
Done initializing train_seqs Dataset
Done initializing val_seqs Dataset
Start of Online Training, sequence: blackswan
Traceback (most recent call last):
  File "train_online.py", line 129, in <module>
    outputs = net.forward(inputs)
  File "/host/workspace/OSVOS-PyTorch/networks/vgg_osvos.py", line 68, in forward
    side.append(center_crop(self.upscale[i - 1](side_temp), crop_h, crop_w))
  File "/host/workspace/OSVOS-PyTorch/layers/osvos_layers.py", line 57, in center_crop
    crop_h.ceil().int()[0], crop_h.floor().int()[0],
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/functional.py", line 1914, in pad
    return ConstantPadNd.apply(input, pad, value)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/_functions/padding.py", line 27, in forward
    output = input.new(input.size()[:(ctx.l_diff)] + new_dim).fill_(ctx.value)
TypeError: torch.Size() takes an iterable of 'int' (item 2 is 'Variable')
```

PyTorch version: `0.4.0a0+71d7321`
Python version: `Python 3.6.4 :: Anaconda, Inc.`

**Comment by mrteera** [comment]
I'm not sure if I fix it correctly:

https://github.com/kmaninis/OSVOS-PyTorch/blob/master/layers/osvos_layers.py#L55
to
```
    return F.pad(x, (int(crop_w.ceil()), int(crop_w.floor()), int(crop_h.ceil()), int(crop_h.floor())))
```

**Comment by scaelles** [comment]
Hello mrteera,
The fix that you have applied looks good to me. We have only tested our code in stable released versions of Pytorch (0.2, 0.3, 0.3.1) and we haven't encountered that error previously so I guess they have change the behavior of the pad function. If the code works after your fix, please close the issue.
Best

**Comment by mrteera** [comment]
I have another error. I'm not sure if it comes from my fix or not.

```
[Epoch: 10000, numImages:     1]
Loss: 1109.525879
Online training time: 1661.821477145073
Testing Network
train_online.py:182: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  inputs, gts = Variable(img, volatile=True), Variable(gt, volatile=True)
```

**Comment by scaelles** [comment]
We were using volatile=True to use less memory at test time as no gradient has to be computed. The message you get is just a warning so it should work anyway. I recommend you to use the latest release (0.3.1) so you don't have to worry about changes in the API done in the version that you use now.

**Comment by kmaninis** [comment]
Hi, once PyTorch 0.4 is stable and released, we will make all our code compatible to that. I hope this helps.
