### ISSUE TITLE
train_seqs.txt and val_seqs.txt

### ISSUE THREAD

**Issue by Agile-yun** [kmaninis/OSVOS-PyTorch#9]
I tried to train the parent network using DAVIS-2016 dataset.
It needs the train_seqs.txt and val_seqs.txt files.
But, I cannot find these text file in DAVIS-2016 dataset.
Can you provide these txt files?
I think these files have a folder name in dataset, right?

**Comment by scaelles** [comment]
Hello,
Here are the files, just place them in the db_root_dir() directory.
[train_seqs.txt](https://github.com/kmaninis/OSVOS-PyTorch/files/1938742/train_seqs.txt)
[val_seqs.txt](https://github.com/kmaninis/OSVOS-PyTorch/files/1938743/val_seqs.txt)
Let us know if you have any other issue!
